version: 2.1

# Define the environment parameter
parameters:
  environment:
    type: string
    default: "staging"
    
# Define jobs
jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Display Current Branch
          command: |
            echo "Current branch: ${CIRCLE_BRANCH}"
      - run:
          name: Install Dependencies
          command: |
            echo "Installing dependencies..."
            # npm install  # Uncommented when actually using Node.js
      - run:
          name: Run Unit Tests
          command: |
            echo "Running tests..."
            # npm test    # Uncommented when actually using Node.js

  deploy:
    docker:
      - image: cimg/node:18.0
    parameters:
      environment:
        type: string
        default: "1111"
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: |
            echo "Deploying to << parameters.environment >> environment"
      - when:
          condition:
            equal: [ "production", << parameters.environment >> ]
          steps:
            - run:
                name: Production-only Step
                command: |
                  echo "Running production-specific tasks..."

# Define workflow
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build # This will run for all branches
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: workshop/circleci # Only run deploy job on main branch
          context: deployment